name = "MyExample"
uuid = "bcd2c276-2ef1-4c6a-aaad-b35b1e17870d"
authors = ["John Ferrier"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
